name : Readme checker

on:
  pull_request:
    branches:
      - main


jobs:
  call-super-linter:
    name: Call Super-Linter
    steps:
      - uses: bretfisher/super-linter-workflow/.github/workflows/reusable-super-linter.yaml@main
